### ISSUE TITLE
Why isn't this feedstock a `noarch`?

### ISSUE THREAD

**Issue by anjos** [conda-forge/nox-feedstock#23]
### Comment:

I'm trying to install this feedstock on osx-arm64 to no avail (actually, it installs an old version from 2021).

I was about to issue a migration request, but I think this package should probably be set as `noarch`, as it seems to fit all requirements for this (https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds).  Are there any reasons blocking this?

**Comment by kynan** [comment]
No good reason, let me switch to `noarch`.

**Comment by kynan** [comment]
Wait, there was a good reason: unfortunately the recipe [requires selectors](https://github.com/conda-forge/nox-feedstock/blob/main/recipe/meta.yaml#L28), which are incompatible with noarch builds 😞

**Comment by anjos** [comment]
Right - thanks for the info.  I'll issue a migration request.
